#############################################################################
# Makefile for building: proj1.app/Contents/MacOS/proj1
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  proj1.pro
# Template: app
# Command: /Users/pro/Qt5.14.2/5.14.2/clang_64/bin/qmake -o Makefile proj1.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib
QMAKE         = /Users/pro/Qt5.14.2/5.14.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/pro/Qt5.14.2/5.14.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/pro/Qt5.14.2/5.14.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = proj11.0.0
DISTDIR = /Users/pro/Desktop/proj1/.tmp/proj11.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/pro/Qt5.14.2/5.14.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = addedfunctions.cpp \
		adminui.cpp \
		buyer.cpp \
		buygood.cpp \
		file.cpp \
		good.cpp \
		info.cpp \
		launchgood.cpp \
		list.cpp \
		logindlg.cpp \
		main.cpp \
		mainwindow.cpp \
		manual.cpp \
		modify.cpp \
		order.cpp \
		recharge.cpp \
		register.cpp \
		remove.cpp \
		search.cpp \
		seller.cpp \
		test.cpp \
		user.cpp \
		userui.cpp qrc_myResources.cpp \
		moc_adminui.cpp \
		moc_buyer.cpp \
		moc_buygood.cpp \
		moc_info.cpp \
		moc_launchgood.cpp \
		moc_logindlg.cpp \
		moc_mainwindow.cpp \
		moc_manual.cpp \
		moc_modify.cpp \
		moc_recharge.cpp \
		moc_register.cpp \
		moc_remove.cpp \
		moc_search.cpp \
		moc_seller.cpp \
		moc_userui.cpp
OBJECTS       = addedfunctions.o \
		adminui.o \
		buyer.o \
		buygood.o \
		file.o \
		good.o \
		info.o \
		launchgood.o \
		list.o \
		logindlg.o \
		main.o \
		mainwindow.o \
		manual.o \
		modify.o \
		order.o \
		recharge.o \
		register.o \
		remove.o \
		search.o \
		seller.o \
		test.o \
		user.o \
		userui.o \
		qrc_myResources.o \
		moc_adminui.o \
		moc_buyer.o \
		moc_buygood.o \
		moc_info.o \
		moc_launchgood.o \
		moc_logindlg.o \
		moc_mainwindow.o \
		moc_manual.o \
		moc_modify.o \
		moc_recharge.o \
		moc_register.o \
		moc_remove.o \
		moc_search.o \
		moc_seller.o \
		moc_userui.o
DIST          = ../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/qdevice.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/unix.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/macx.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/qconfig.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_post.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources_functions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/moc.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/uic.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/lex.prf \
		proj1.pro addedfunctions.h \
		adminui.h \
		buyer.h \
		buygood.h \
		file.h \
		good.h \
		info.h \
		launchgood.h \
		list.h \
		logindlg.h \
		mainwindow.h \
		manual.h \
		modify.h \
		order.h \
		recharge.h \
		register.h \
		remove.h \
		search.h \
		seller.h \
		test.h \
		user.h \
		userui.h addedfunctions.cpp \
		adminui.cpp \
		buyer.cpp \
		buygood.cpp \
		file.cpp \
		good.cpp \
		info.cpp \
		launchgood.cpp \
		list.cpp \
		logindlg.cpp \
		main.cpp \
		mainwindow.cpp \
		manual.cpp \
		modify.cpp \
		order.cpp \
		recharge.cpp \
		register.cpp \
		remove.cpp \
		search.cpp \
		seller.cpp \
		test.cpp \
		user.cpp \
		userui.cpp
QMAKE_TARGET  = proj1
DESTDIR       = 
TARGET        = proj1.app/Contents/MacOS/proj1

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/pro/Desktop/proj1/proj1.pro


include /Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

proj1.app/Contents/MacOS/proj1: ui_adminui.h ui_buyer.h ui_buygood.h ui_info.h ui_launchgood.h ui_logindlg.h ui_mainwindow.h ui_manual.h ui_modify.h ui_recharge.h ui_register.h ui_remove.h ui_search.h ui_seller.h ui_userui.h $(OBJECTS)  
	@test -d proj1.app/Contents/MacOS/ || mkdir -p proj1.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: proj1.pro ../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/qdevice.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/unix.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/macx.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/qconfig.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_post.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources_functions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/moc.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/uic.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/lex.prf \
		proj1.pro \
		myResources.qrc \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile proj1.pro
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/qdevice.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/device_config.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/unix.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/mac.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/macx.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/sanitize.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/qconfig.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/spec_post.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/toolchain.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/default_post.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/mac.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qt.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources_functions.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/resources.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/moc.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/uic.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/qmake_use.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/file_copies.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/yacc.prf:
../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/lex.prf:
proj1.pro:
myResources.qrc:
../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile proj1.pro

qmake_all: FORCE

proj1.app/Contents/PkgInfo: 
	@test -d proj1.app/Contents || mkdir -p proj1.app/Contents
	@$(DEL_FILE) proj1.app/Contents/PkgInfo
	@echo "APPL????" > proj1.app/Contents/PkgInfo
proj1.app/Contents/Resources/empty.lproj: 
	@test -d proj1.app/Contents/Resources || mkdir -p proj1.app/Contents/Resources
	@touch proj1.app/Contents/Resources/empty.lproj
	
proj1.app/Contents/Info.plist: 
	@test -d proj1.app/Contents || mkdir -p proj1.app/Contents
	@$(DEL_FILE) proj1.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,guqiuhan.proj1,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},guqiuhan.proj1,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,proj1,g" -e "s,@LIBRARY@,proj1,g" -e "s,\$${EXECUTABLE_NAME},proj1,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang/Info.plist.app >proj1.app/Contents/Info.plist

all: Makefile \
		proj1.app/Contents/PkgInfo \
		proj1.app/Contents/Resources/empty.lproj \
		proj1.app/Contents/Info.plist proj1.app/Contents/MacOS/proj1

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents myResources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents addedfunctions.h adminui.h buyer.h buygood.h file.h good.h info.h launchgood.h list.h logindlg.h mainwindow.h manual.h modify.h order.h recharge.h register.h remove.h search.h seller.h test.h user.h userui.h $(DISTDIR)/
	$(COPY_FILE) --parents addedfunctions.cpp adminui.cpp buyer.cpp buygood.cpp file.cpp good.cpp info.cpp launchgood.cpp list.cpp logindlg.cpp main.cpp mainwindow.cpp manual.cpp modify.cpp order.cpp recharge.cpp register.cpp remove.cpp search.cpp seller.cpp test.cpp user.cpp userui.cpp $(DISTDIR)/
	$(COPY_FILE) --parents adminui.ui buyer.ui buygood.ui info.ui launchgood.ui logindlg.ui mainwindow.ui manual.ui modify.ui recharge.ui register.ui remove.ui search.ui seller.ui userui.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r proj1.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_myResources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_myResources.cpp
qrc_myResources.cpp: myResources.qrc \
		../../Qt5.14.2/5.14.2/clang_64/bin/rcc \
		order.txt \
		user.txt \
		good.txt \
		2.jpg \
		1.jpg
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/rcc -name myResources myResources.qrc -o qrc_myResources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h ../../Qt5.14.2/5.14.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_adminui.cpp moc_buyer.cpp moc_buygood.cpp moc_info.cpp moc_launchgood.cpp moc_logindlg.cpp moc_mainwindow.cpp moc_manual.cpp moc_modify.cpp moc_recharge.cpp moc_register.cpp moc_remove.cpp moc_search.cpp moc_seller.cpp moc_userui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_adminui.cpp moc_buyer.cpp moc_buygood.cpp moc_info.cpp moc_launchgood.cpp moc_logindlg.cpp moc_mainwindow.cpp moc_manual.cpp moc_modify.cpp moc_recharge.cpp moc_register.cpp moc_remove.cpp moc_search.cpp moc_seller.cpp moc_userui.cpp
moc_adminui.cpp: adminui.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib adminui.h -o moc_adminui.cpp

moc_buyer.cpp: buyer.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		user.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib buyer.h -o moc_buyer.cpp

moc_buygood.cpp: buygood.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		user.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib buygood.h -o moc_buygood.cpp

moc_info.cpp: info.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		user.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib info.h -o moc_info.cpp

moc_launchgood.cpp: launchgood.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib launchgood.h -o moc_launchgood.cpp

moc_logindlg.cpp: logindlg.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		register.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		user.h \
		good.h \
		order.h \
		adminui.h \
		userui.h \
		seller.h \
		buyer.h \
		info.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib logindlg.h -o moc_logindlg.cpp

moc_mainwindow.cpp: mainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_manual.cpp: manual.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib manual.h -o moc_manual.cpp

moc_modify.cpp: modify.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		user.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib modify.h -o moc_modify.cpp

moc_recharge.cpp: recharge.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib recharge.h -o moc_recharge.cpp

moc_register.cpp: register.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		user.h \
		good.h \
		order.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib register.h -o moc_register.cpp

moc_remove.cpp: remove.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib remove.h -o moc_remove.cpp

moc_search.cpp: search.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib search.h -o moc_search.cpp

moc_seller.cpp: seller.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		user.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib seller.h -o moc_seller.cpp

moc_userui.cpp: userui.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		user.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		seller.h \
		buyer.h \
		info.h \
		moc_predefs.h \
		../../Qt5.14.2/5.14.2/clang_64/bin/moc
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/moc $(DEFINES) --include /Users/pro/Desktop/proj1/moc_predefs.h -I/Users/pro/Qt5.14.2/5.14.2/clang_64/mkspecs/macx-clang -I/Users/pro/Desktop/proj1 -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers -I/Users/pro/Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/pro/Qt5.14.2/5.14.2/clang_64/lib userui.h -o moc_userui.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_adminui.h ui_buyer.h ui_buygood.h ui_info.h ui_launchgood.h ui_logindlg.h ui_mainwindow.h ui_manual.h ui_modify.h ui_recharge.h ui_register.h ui_remove.h ui_search.h ui_seller.h ui_userui.h
compiler_uic_clean:
	-$(DEL_FILE) ui_adminui.h ui_buyer.h ui_buygood.h ui_info.h ui_launchgood.h ui_logindlg.h ui_mainwindow.h ui_manual.h ui_modify.h ui_recharge.h ui_register.h ui_remove.h ui_search.h ui_seller.h ui_userui.h
ui_adminui.h: adminui.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic adminui.ui -o ui_adminui.h

ui_buyer.h: buyer.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic buyer.ui -o ui_buyer.h

ui_buygood.h: buygood.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic buygood.ui -o ui_buygood.h

ui_info.h: info.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic info.ui -o ui_info.h

ui_launchgood.h: launchgood.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic launchgood.ui -o ui_launchgood.h

ui_logindlg.h: logindlg.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic logindlg.ui -o ui_logindlg.h

ui_mainwindow.h: mainwindow.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_manual.h: manual.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic manual.ui -o ui_manual.h

ui_modify.h: modify.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic modify.ui -o ui_modify.h

ui_recharge.h: recharge.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic recharge.ui -o ui_recharge.h

ui_register.h: register.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic register.ui -o ui_register.h

ui_remove.h: remove.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic remove.ui -o ui_remove.h

ui_search.h: search.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic search.ui -o ui_search.h

ui_seller.h: seller.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic seller.ui -o ui_seller.h

ui_userui.h: userui.ui \
		../../Qt5.14.2/5.14.2/clang_64/bin/uic
	/Users/pro/Qt5.14.2/5.14.2/clang_64/bin/uic userui.ui -o ui_userui.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

addedfunctions.o: addedfunctions.cpp addedfunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addedfunctions.o addedfunctions.cpp

adminui.o: adminui.cpp adminui.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		ui_adminui.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		logindlg.h \
		register.h \
		user.h \
		order.h \
		userui.h \
		seller.h \
		buyer.h \
		info.h \
		search.h \
		remove.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminui.o adminui.cpp

buyer.o: buyer.cpp buyer.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		user.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		ui_buyer.h \
		search.h \
		buygood.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buyer.o buyer.cpp

buygood.o: buygood.cpp buygood.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		user.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		ui_buygood.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buygood.o buygood.cpp

file.o: file.cpp file.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		user.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		good.h \
		order.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file.o file.cpp

good.o: good.cpp good.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		user.h \
		list.h \
		order.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o good.o good.cpp

info.o: info.cpp info.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		user.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		ui_info.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		recharge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o info.o info.cpp

launchgood.o: launchgood.cpp launchgood.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		ui_launchgood.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o launchgood.o launchgood.cpp

list.o: list.cpp list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o list.o list.cpp

logindlg.o: logindlg.cpp logindlg.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		register.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		user.h \
		good.h \
		order.h \
		adminui.h \
		userui.h \
		seller.h \
		buyer.h \
		info.h \
		ui_logindlg.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		manual.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logindlg.o logindlg.cpp

main.o: main.cpp mainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		logindlg.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		register.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		user.h \
		good.h \
		order.h \
		adminui.h \
		userui.h \
		seller.h \
		buyer.h \
		info.h \
		file.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

manual.o: manual.cpp manual.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_manual.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manual.o manual.cpp

modify.o: modify.cpp modify.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		user.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		ui_modify.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modify.o modify.cpp

order.o: order.cpp order.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		user.h \
		list.h \
		good.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o order.o order.cpp

recharge.o: recharge.cpp recharge.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_recharge.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recharge.o recharge.cpp

register.o: register.cpp register.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		user.h \
		good.h \
		order.h \
		ui_register.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o register.o register.cpp

remove.o: remove.cpp remove.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_remove.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o remove.o remove.cpp

search.o: search.cpp search.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_search.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o search.o search.cpp

seller.o: seller.cpp seller.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		user.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		ui_seller.h \
		launchgood.h \
		modify.h \
		remove.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/QStandardItemModel \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o seller.o seller.cpp

test.o: test.cpp test.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		user.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		good.h \
		order.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

user.o: user.cpp user.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

userui.o: userui.cpp userui.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qstring.h \
		user.h \
		list.h \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt5.14.2/5.14.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		good.h \
		order.h \
		seller.h \
		buyer.h \
		info.h \
		ui_userui.h \
		logindlg.h \
		register.h \
		adminui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userui.o userui.cpp

qrc_myResources.o: qrc_myResources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_myResources.o qrc_myResources.cpp

moc_adminui.o: moc_adminui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminui.o moc_adminui.cpp

moc_buyer.o: moc_buyer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buyer.o moc_buyer.cpp

moc_buygood.o: moc_buygood.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buygood.o moc_buygood.cpp

moc_info.o: moc_info.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_info.o moc_info.cpp

moc_launchgood.o: moc_launchgood.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_launchgood.o moc_launchgood.cpp

moc_logindlg.o: moc_logindlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logindlg.o moc_logindlg.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_manual.o: moc_manual.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_manual.o moc_manual.cpp

moc_modify.o: moc_modify.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modify.o moc_modify.cpp

moc_recharge.o: moc_recharge.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_recharge.o moc_recharge.cpp

moc_register.o: moc_register.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_register.o moc_register.cpp

moc_remove.o: moc_remove.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_remove.o moc_remove.cpp

moc_search.o: moc_search.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_search.o moc_search.cpp

moc_seller.o: moc_seller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_seller.o moc_seller.cpp

moc_userui.o: moc_userui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userui.o moc_userui.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/proj1/bin || mkdir -p $(INSTALL_ROOT)/opt/proj1/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/proj1/bin/proj1.app
	
	$(QINSTALL) proj1.app $(INSTALL_ROOT)/opt/proj1/bin/proj1.app
	-$(STRIP) $(INSTALL_ROOT)/opt/proj1/bin/proj1.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/proj1/bin/proj1.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/proj1/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

